### ISSUE TITLE
Add different exit codes for WARNING and INFO

### ISSUE THREAD

**Issue by idahogray** [riseclipse/riseclipse-validator-scl2003#134]
IEC 61850-6-3 is making use of ERROR, WARNING, and INFO messages for OCL invariants. Would it be possible to change the exit code according to the message type?

| Message Type | Exit Code |
|-----------------|------------|
| ERROR             | 1              |
| WARNING       | 2              |
| INFO               | 3              |

This will help us verify the correct type of message was used for a given invariant during our automated tests.

**Comment by marcadetd** [comment]
@idahogray  I propose to make this behavior available with a specific option on the command line.
Also, to be more in line with RFC 5424, NOTICE will be added with value 3 (and INFO will have value 4).
Is it OK?

**Comment by keith-gray-powereng** [comment]
Sorry, I used a different account to create this issue. Anyway, I think a command line option is fine for IEC 61850-6-3.

**Comment by marcadetd** [comment]
Available in 4029409
