### ISSUE TITLE
DO.Name and SDO.name shall be a combination of the abbreviations listed in 7-4 NSD file (WARNING)

### ISSUE THREAD

**Issue by ADehouck** [riseclipse/riseclipse-validator-scl2003#145]
See in IEC 61850-7-1 ed2.1 §A.1.3:

![image](https://github.com/riseclipse/riseclipse-metamodel-nsd2016/assets/62877587/c665347f-2cda-4c8c-8446-1e5c6c4ee2b9)

The abbreviation list can be found in NSD file of IEC 61850-7-4 (no need to look for the namespace to find the correct version of 7-4 to apply : just use the latest one available), this rule also apply for extension DO/SDO names

![image](https://github.com/riseclipse/riseclipse-metamodel-nsd2016/assets/62877587/98bf99d2-ecc0-41e3-9c45-bde64046721c)

**Comment by marcadetd** [comment]
There are a lot of SDO named "phsA": this is not valid?
And we assume that digits at the end of the name are ignored for this check?

**Comment by ADehouck** [comment]
Could the DO of Extended LN also be checked regarding the abbreviations ?

Example : This file defines an extended LN containing a DO which name is not a combination of standard abbreviations, and no Warning is raised : 
[LN_extension_DOAbbErr.txt](https://github.com/user-attachments/files/16159687/LN_extension_DOAbbErr.txt)



![image](https://github.com/riseclipse/riseclipse-validator-scl2003/assets/62877587/354c7706-c882-4b43-adca-b296b9c2ad9c)

**Comment by ADehouck** [comment]
In addition, the error messages on that check are duplicated multiple times,

example for this file : [DOExtension.txt](https://github.com/user-attachments/files/16159730/DOExtension.txt)

the same error is raised multiple times

![image](https://github.com/riseclipse/riseclipse-validator-scl2003/assets/62877587/2909135d-38ae-4721-8538-88860cdcedd1)

**Comment by marcadetd** [comment]
LNodeType id="PPPP1" is referred by an LN which is in an unknown namespace ("Private"), therefore it is not checked.

**Comment by marcadetd** [comment]
Verification of DO names are now done even in unknown namespaces (commit [bb39e11](https://github.com/riseclipse/riseclipse-validator-scl2003/pull/173/commits/bb39e11f75e8dd2ed84c576af3fdbd12ed35064c))
