### ISSUE TITLE
No ERRORS should be raised when mandatory, but deprecated DO are not present in the file

### ISSUE THREAD

**Issue by ADehouck** [riseclipse/riseclipse-validator-scl2003#162]
Example : this file defines a LN "DGEN" this way :
[Mandatory_Deprecated_DO_absent.txt](https://github.com/user-attachments/files/16159428/Mandatory_Deprecated_DO_absent.txt)

![image](https://github.com/riseclipse/riseclipse-validator-scl2003/assets/62877587/daf2d94b-8971-476c-8b96-63cced2b3030)

In the NSD file, the DO "GnOpSt" and "OpTmsRs" are defined as Mandatory (prescond="M"), but they are also defined as deprecated (deprecated="true")

![image](https://github.com/riseclipse/riseclipse-validator-scl2003/assets/62877587/fc4efa5d-701e-4ba7-848e-0365181e8a3d)

Currently, RiseClipse raised this ERRORS,

But they should not be raised, as these DOs are deprecated

> ERROR: [NSD/Validation/DataObject] DO "GnOpSt" is mandatory in LNodeType id=DGEN1 with LNClass "DGEN" in namespace "IEC 61850-7-420:2019A" at line 334

> ERROR: [NSD/Validation/DataObject] DO "OpTmsRs" is mandatory in LNodeType id=DGEN1 with LNClass "DGEN" in namespace "IEC 61850-7-420:2019A" at line 334

**Comment by marcadetd** [comment]
Is it only when mandatory? What to do for a DO present, but declared forbidden and deprecated in NSD?

**Comment by ADehouck** [comment]
A DO that is present, but declared forbidden and deprecated in NSD will raise a WARNING because of "https://github.com/riseclipse/riseclipse-validator-scl2003/issues/163" ? but should not raise another ERROR I think
