### ISSUE TITLE
Raise a WARNING when a DO is deprecated

### ISSUE THREAD

**Issue by ADehouck** [riseclipse/riseclipse-validator-scl2003#163]
A WARNING should be raised when a DO is used whereas it is deprecated in the NSD file : 

Example, this file defines a DGEN containing the DO "OpTmsRs", [DO_Deprecated_raiseWarning.txt](https://github.com/user-attachments/files/16159523/DO_Deprecated_raiseWarning.txt)

In the corresponding NSD, this DO is defined as deprecated (deprecated="true")

The user should be warned that a deprecated DO was used

![image](https://github.com/riseclipse/riseclipse-validator-scl2003/assets/62877587/4484572d-baa2-4946-b918-ee01d892d64f)

---

![image](https://github.com/riseclipse/riseclipse-validator-scl2003/assets/62877587/b4aae306-a091-4ead-ba35-ac6ac386cc88)

**Comment by marcadetd** [comment]
should have been closed...
