### ISSUE TITLE
Improve output report by using separated results

### ISSUE THREAD

**Issue by cvenditti-tmw** [riseclipse/riseclipse-validator-scl2003#17]
The actual format of the report might be difficult to parse by external tool. Semicolon separated results might also be beneficial if the data needs to be viewed in Excel.

**Comment by marcadetd** [comment]
Thanks for this issue.
Could you give an example (one line is enough) showing the current output and the expected one ?

**Comment by cvenditti-tmw** [comment]
Current output:
ERROR:   [SemanticConstraints] DOI (name=Beh) (line 413) does not refer an existing DO in DataTypeTemplates section

Expected output (example):
ERROR;SemanticConstraints;DOI;name=Beh;413;does not refer an existing DO in DataTypeTemplates section

Thank you

**Comment by ADehouck** [comment]
It could also be interesting to add an identifier for each rule, what do you think ?
several options for this identifer:

- constructed/structured ID - to define (example : T1 for rules on Terminals, S1 for rules on Substations...)
- GUID : globally unique identifier (example : 3F2504E0-4F89-11D3-9A0C-0305E82C3301), but maybe not very nice for human reading

Expected output (example):
Severity;ID;Namespace;Category;LineNumber;Message
ERROR;S1;SemanticConstraints;413;DOI name=Beh does not refer an existing DO in DataTypeTemplates section

**Comment by marcadetd** [comment]
There are not only OCL validation messages, there are also, for example, those from NSD validation.
Could we use hierarchically organized categories?
ERROR;OCL/SemanticConstraints/Subtation;413;DOI name=Beh does not refer an existing DO in DataTypeTemplates section

**Comment by ADehouck** [comment]
Proposition of structure:
with a separator ;

error level : INFO, WARNING, ERROR, CRITICAL
OCL rule identifier (textual unique name of the rule)
Namespace (IEC61850-6 by default)
hierarchically organized category (example : OCL/… or NSD/…)
Line number
error message text

Example:
ERROR;unique_LN_reference_in_Substation_LNode;IEC61850-6;OCL/SemanticConstraints/Subtation;413;LN reference from LNode element in Substation shall be unique in the Substation

**Comment by marcadetd** [comment]
Current message levels are VERBOSE, INFO, WARNING, ERROR, FATAL. The last one will stop the tool. Is CRITICAL also needed (between ERROR and FATAL) ?
When will the namespace not be the default one ?

**Comment by ADehouck** [comment]
More precisions : the idea would be to use the standard severity levels form Syslog (standard for message logging):
https://en.wikipedia.org/wiki/Syslog

We could use this restricted list:

- debug (instead of VERBOSE ?): Messages that contain information normally of use only when debugging a program
- info : confirmation that the program is working as expected
- notice: conditions that are not error conditions, but may require special handling
- warning
- error
- emerg (instead of FATAL ?): system is unusable

Regarding the namespace, it may be different from the default one, when new extensions of SCL will be defined by the standard (for example : 61850-6-100)

**Comment by marcadetd** [comment]
OK for Syslog severity levels, the full list will be provided even if only some of them will be used.

I would prefer to keep RiseClipse messages neutral (not specific to SCL), so if we keep :

> - syslog level
> - hierarchically organized identifier: uniqueness is not required (not easy for explicit links or NSD messages) but can be obtained for OCL (using the name of the OCL rule as the last part)
> - line number (with optional filename)
> - error message text
> 

Is si OK ?

If the need arises, a specific SCL message, adding the namespace, can be proposed.
