### ISSUE TITLE
Add a page that lists all the error messages that can be raised by the NSD validation

### ISSUE THREAD

**Issue by ADehouck** [riseclipse/riseclipse-validator-scl2003#175]
Create a list of possible error messages by category, and severity, and add it on https://riseclipse.github.io/ 

Maybe a new page "Documentation", referenced "RiseClipse other topics"

First attempt :

| Category  | Severity | Error message | 
| ------------- | ------------- |------------- |
| NSD/Validation | ERROR | AnyLN type="xxx" class="yyy" has no namespace at line nnn|
| NSD/Validation | ERROR | LNClassValidator xxx not found for LNodeType in namespace "yyy" at line nnn |
| NSD/Validation | WARNING  | Cannot validate AnyLN type="xxx" class="yyy" in namespace "zzz" because this namespace is unknown at line nnn |
| NSD/Validation/LNClass | WARNING  | DO name "xxx" is not composed using standardised abbreviations at line nnn |
| NSD/Validation/CDC | ERROR| SDO xxx has a count attribute while the corresponding SubDataObject has not isArray="true" in namespace "yyy" at line nnn |
| NSD/Validation/CDC | WARNING | SDO name "xxx" is not composed using standardised abbreviations at line nnn |
| NSD/Validation/CDC | WARNING | DA xxx of type yyy cannot be verified because there is no validator for it in namespace "zzz" at line nnn |
| NSD/Validation/CDC | ERROR | Attribute dupd/dchg/qchg of DA xxx is true while the corresponding one in DataAttribute is false or absent in namespace "yyy" at line nnn|
| NSD/Validation/DataObject | ERROR|  DO "xxx" is mandatory in LNodeType id=yyy with LNClass "zzz" in namespace "aaa" at line nnn|
| NSD/Validation/DataObject | ERROR|  DO "xxx" in LNodeType id "yyy" not found in LNClass "zzz" in namespace "aaa" at line nnn |
| NSD/Validation/DataAttribute | ERROR|  DA "xxx" is mandatory in DOType in namespace "yyy" because there are sibling elements of type zzz which includes 'aaa' as a child at line nnn|
| NSD/Validation/DataAttribute | ERROR|  DA "ldNs" is forbidden in DOType with LNClass xxx at line nnn in namespace "yyy" at line nnn|
| NSD/Validation/Enumeration| ERROR|  EnumVal with ord "iii" in EnumType id = xxx is not defined as LiteralVal in standard Enumeration yyy in namespace "zzz" at line nnn|
| NSD/Validation/Enumeration| ERROR|  EnumVal with ord "iii" in EnumType id = xxx  has incorrect name "yyy" instead of "zzz" in standard enumeration aaa in namespace "bbb" at line nnn |
| NSD/Validation/BasicType | ERROR|  type of DA/BDA "xxx" is not "yyy", it is "zzz" at line nnn |
| NSD/Validation/BasicType | ERROR|  empty value of Val in DAI "xxx" is not valid for "yyy" type at line nnn|

**Comment by marcadetd** [comment]
Put it in the repository where the messages are defined so that changes can be synchronized
