### ISSUE TITLE
Make the collection of FCDA in DataSet serialized

### ISSUE THREAD

**Issue by sina-kariminet** [riseclipse/riseclipse-validator-scl2003#191]
We are using OCL to verify the integrity of a configured SCD. One of the steps is verifying the order of FCDAs in a dataset matches an expected list.

At this time the collection of FCDAs seems to be random.

**Comment by marcadetd** [comment]
Hi,
The FCDA are now ordered, and there is also an attribute which gives the index of the FCDA (see https://github.com/riseclipse/riseclipse-metamodel-scl2003/issues/52).
Are you using the latest version (1.2.8) of the validator ?
