### ISSUE TITLE
Undue error raised by RiseClipse on EnumType id's value

### ISSUE THREAD

**Issue by ADehouck** [riseclipse/riseclipse-validator-scl2003#78]
The id's value of EnumTypes in DataTypeTemplates are not normative, 
the error bellow should not be raised:

ERROR:  [NSD validation] EnumType (id = EnType_Multiplier_V99) at line 4982 must use MultiplierKind as id because it is identical to the standard Enumeration

Extract of the SCL file, in DataTypeTemplates section
`<EnumType id="EnType_Multiplier_V99">`
      `<EnumVal ord="-24">y</EnumVal>`
    `  <EnumVal ord="-21">z</EnumVal>`
     ` <EnumVal ord="-18">a</EnumVal>`
     ` <EnumVal ord="-15">f</EnumVal>`

**Comment by marcadetd** [comment]
This issue has been corrected by commit ccd2788265d9471691a1c0e20c59ee6fa3f899ec on Feb 11, 2020
