### ISSUE TITLE
Add the verification of predCond=MFscaledAV

### ISSUE THREAD

**Issue by ADehouck** [riseclipse/riseclipse-validator-scl2003#94]
MFscaledAV means : "Element is mandatory if any sibling elements of type AnalogueValue include 'i' as a child, otherwise forbidden."

Example:

`<CDC name="MV" titleID="IEC 61850-7-3:MV.title">`
`<DataAttribute name="sVC" fc="CF" type="ScaledValueConfig" typeKind="CONSTRUCTED" dchg="true" descID="IEC 61850-7-3:MV.sVC.desc" presCond="MFscaledAV"/>`

**Comment by marcadetd** [comment]
fix by PR #97
